### ISSUE TITLE
CharactersInterface

### ISSUE THREAD

**Issue by nerdoc** [metroplex-systems/edifact#3]
Just a question: why did you create an Interface for the Characters? is it supposed to have more than one implementation? Or just for encapsulation purposes?

**Comment by duncan3dc** [comment]
Hi @nerdoc

I always try to follow best practices and not depend on concrete classes, it makes the code flexible and able to support use cases I might not have thought of when I write it.

In this specific case, I originally did it so that people could produce their own concrete class using their standard default control characters. However recently I've been making use of it when looking into [TRADACOMS](https://github.com/metroplex-systems/edifact/blob/df6610c31bf2e09d7231869ba5a80841e7063a0f/src/Control/Tradacoms.php)

**Comment by nerdoc** [comment]
Thanks!
